- name: Create dynamo table with hash key
  community.aws.dynamodb_table:
    name: "{{ demo_table_name }}"
    region: "{{ region }}"
    hash_key_name: id
    hash_key_type: STRING
    read_capacity: 2
    write_capacity: 2
    tags:
      tag_name: demo_table
