---
- name: Zip Lambda Code 
  archive:
    path: "code/{{ item }}.py"
    dest: "{{ item }}.zip"
    format: zip
  with_items:
  - get_data
  - insert_data

- name: Create S3 Bucket
  amazon.aws.s3_bucket:
    name: "{{ code_bucket_name }}"
    region: "{{ region }}"
    state: present

- name: Copy Archive to S3 Bucket
  amazon.aws.aws_s3:
    bucket: "{{ code_bucket_name }}"
    object: "{{ item }}.zip"
    src: "{{ item }}.zip"
    mode: put
  with_items:
  - get_data
  - insert_data

