---
- name: Create S3 Bucket
  amazon.aws.s3_bucket:
    name: "{{ code_bucket_name }}"
    state: present

- name: Zip Code 
  archive:
    path: code/index.py
    dest: roles/s3/files/python-sample.zip
    format: zip

- name: Copy Sample Code to S3 Bucket
  amazon.aws.aws_s3:
    bucket: "{{ code_bucket_name }}"
    object: python-sample.zip
    src: roles/s3/files/python-sample.zip
    mode: put
