- name: Convert Jinja2 Template of Swaager
  template:
    src: swagger.yml.j2
    dest: swagger.yml
    
- name: Setup AWS API Gateway setup on AWS and deploy API definition
  community.aws.aws_api_gateway:
    region: "{{ region }}"
    swagger_file: swagger.yml
    stage: dev
    cache_enabled: true
    cache_size: '1.6'
    tracing_enabled: true
    endpoint_type: EDGE
    state: present
  register: api_gateway_resource

- name: Set API Gateway Domain Name
  set_fact:
    apigw_domain_name: "{{ api_gateway_resource.api_id }}.execute-api.{{ region }}.amazonaws.com"

- name: Display API Gateway Domain Name 
  debug:
    var: apigw_domain_name
