- name: Lambda API GW Invocation For Get Data
  community.aws.lambda_policy:
    state: present
    function_name: get_data
    region: "{{ region }}"
    statement_id: get-data-lambda-api-invocation-1
    action: lambda:InvokeFunction
    principal: apigateway.amazonaws.com
    source_arn: "arn:aws:execute-api:{{ region }}:{{ account_number }}:{{ api_gateway_resource.api_id }}/*/GET/*"

- name: Lambda API GW Invocation for Post Data
  community.aws.lambda_policy:
    state: present
    function_name: insert_data
    region: "{{ region }}"
    statement_id: post-data-lambda-api-invocation-1
    action: lambda:InvokeFunction
    principal: apigateway.amazonaws.com
    source_arn: "arn:aws:execute-api:{{ region }}:{{ account_number }}:{{ api_gateway_resource.api_id }}/*/POST/"
