swagger: '2.0'
info:
  description: A Simple IP Address API
  title: Sample API 
  version: v1
host: localhost
schemes:
  - http
  - https

basePath: /

paths:
  /:
    get:
      summary: Get All details
      responses:
        '200':
          description: Success response
          schema:
            type: object
            properties:
              ip:
                type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:281735606975:function:HelloWorld/invocations"
        credentials: arn:aws:iam::281735606975:role/service-role/python-sample-template-role-x79qi0ie
        httpMethod: "POST"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
