# Create Lambda functions
- name: Create Lambda Functions
  community.aws.lambda:
    name: '{{ item }}'
    state: present
    s3_bucket: "{{ code_bucket_name }}"
    s3_key: "{{ item }}.zip"
    runtime: 'python3.8'
    role:  "{{ iam_role_ddb_lambda_arn }}"
    handler: "{{ item }}.lambda_handler"
    region: "{{ region }}"
    environment_variables:
      RDS_Endpoint: "{{ rds_endpoint }}"        
    tags:
      Name: '{{ item }}'
      managed_by: "Ansible"
  with_items:
  - get_data
  - insert_data


